### ISSUE TITLE
Remote host `open` and `xdg-open` do not obey opener config

### ISSUE THREAD

**Issue by ElanHasson** [superbrothers/opener#23]
They are hard coded to use unix sockets, they must be manually modified to use tcp.

**Comment by superbrothers** [comment]
You can change your configuration file to use TCP. However, I recommend using unix domain sockets.

- https://github.com/superbrothers/opener#configuration

**Comment by ElanHasson** [comment]
hmm, i couldn't get it to obey the config file i had. I'll try sockets again.
